image: Visual Studio 2017
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  github_token:
    secure: RAU/MUjUsCxEfK5NRX1iFGtna4JHtz3TGQtIrxbYcF+IrVpKC5ceW73RXtfAjVXV

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $lastTag = git describe --abbrev=0
      Set-AppveyorBuildVariable -Name 'LAST_TAG' -Value $lastTag
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
  
  - cmd: msbuild Pidgin.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal

  - cmd: cinst docfx

  - ps: |
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
      git config --global user.email "benhodgson91@gmail.com"
      git config --global user.name "AppVeyor build server"
      git config --global core.safecrlf false

build:
  project: Pidgin.sln
  verbosity: minimal

after_build:
  - cmd: docfx Pidgin.Docs/docfx.json

after_test:
  - cmd: dotnet run --configuration %CONFIGURATION% --project Pidgin.Bench\Pidgin.Bench.csproj
  - cmd: msbuild Pidgin.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: BenchmarkDotNet.Artifacts
  - path: Pidgin.Docs/_site

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: MMVrVYGgJHFAFV4ENMvXWF2NuioBvUc0NleeHFldSEzDhZrTHxBYoeZEHRwCFwQK
  on:
    appveyor_repo_tag: true

on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master' -or $env:APPVEYOR_REPO_TAG -eq 'true') {
        git clone https://github.com/benjamin-hodgson/Pidgin.git -q --depth 1 --branch gh-pages gh-pages
        Remove-Item "gh-pages\$env:APPVEYOR_REPO_BRANCH" -Recurse -ErrorAction Ignore
        Copy-Item Pidgin.Docs\_site -Destination "gh-pages\$env:APPVEYOR_REPO_BRANCH" -Recurse -Container
        cd gh-pages
        git add "$env:APPVEYOR_REPO_BRANCH"
        (gc index.html) -replace 'https://www.benjamin.pizza/Pidgin/[^/]*/', "https://www.benjamin.pizza/Pidgin/$env:LAST_TAG/" | Out-File index.html
        git add index.html
        git commit --allow-empty -m "Update gh-pages"
        git push -q
      }
