version: 1.0.{build}
configuration: Release

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.1/scripts/obtain/dotnet-install.ps1" -OutFile "dotnet-install.ps1"
  - ps: .\dotnet-install.ps1 -Version 1.0.1

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build --configuration %CONFIGURATION%

test_script:
  - cmd: dotnet test --configuration %CONFIGURATION% Pidgin.Tests\Pidgin.Tests.csproj
  - cmd: dotnet run --configuration %CONFIGURATION% --project Pidgin.Bench\Pidgin.Bench.csproj

after_test:
  - cmd: dotnet pack Pidgin\Pidgin.csproj --configuration %CONFIGURATION% --output ..\nupkgs

artifacts:
  - path: nupkgs
  - path: BenchmarkDotNet.Artifacts
