image: Visual Studio 2017
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $lastTag = git describe --abbrev=0
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
  - cmd: msbuild Pidgin.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal

build:
  project: Pidgin.sln
  verbosity: minimal

after_test:
  - cmd: dotnet run --configuration %CONFIGURATION% --project Pidgin.Bench\Pidgin.Bench.csproj
  - cmd: msbuild Pidgin.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: BenchmarkDotNet.Artifacts

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: MMVrVYGgJHFAFV4ENMvXWF2NuioBvUc0NleeHFldSEzDhZrTHxBYoeZEHRwCFwQK
  on:
    appveyor_repo_tag: true
