configuration: Release
image: Visual Studio 2017

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

before_build:
  - ps: |
      $lastTag = git describe --abbrev=0
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build --configuration %CONFIGURATION%

test_script:
  - cmd: dotnet test --configuration %CONFIGURATION% Pidgin.Tests\Pidgin.Tests.csproj
  - cmd: dotnet run --configuration %CONFIGURATION% --project Pidgin.Bench\Pidgin.Bench.csproj

after_test:
  - cmd: dotnet pack --configuration %CONFIGURATION% --output ..\nupkgs --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER%

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: BenchmarkDotNet.Artifacts

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: MMVrVYGgJHFAFV4ENMvXWF2NuioBvUc0NleeHFldSEzDhZrTHxBYoeZEHRwCFwQK
  on:
    appveyor_repo_tag: true
